export const CONTRACTS = {
  DONATION_ADDRESS: process.env.NEXT_PUBLIC_DONATION_ADDRESS || '',
  TREASURY_ADDRESS: process.env.NEXT_PUBLIC_TREASURY_ADDRESS || '',
  GOVERNANCE_ADDRESS: process.env.NEXT_PUBLIC_GOVERNANCE_ADDRESS || '',
};
